#!/usr/bin/env bash

# VARIABLES ===================================================================

# normalize the PATH stack
export PATH='/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin'

# add Haskell Stack exes to $PATH
export PATH="$HOME/.local/bin:$PATH"

# add local dotfiles scripts
export PATH="$HOME/Projects/dotfiles/bin:$PATH"

# set the default editor to Neovim
export EDITOR=nvim
export VISUAL=nvim



# ALIASES =====================================================================

# shortcuts for the most commonly used tools
alias v='nvim'
alias g='git'

# override common tools with useful arguments
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias dir='dir --color=auto'
alias vdir='vdir --color=auto'
alias ls='ls -FG'
alias la='ls -FGahl'

# attach to the tmux session or create a new named after the user
TMUX_SESSION="$(whoami | sed 's/\./-/g')"
alias t='tmux attach-session -t "$TMUX_SESSION" || tmux new-session -s "$TMUX_SESSION"'

# update all Vim plugins
alias vundle='vim +PlugInstall! +qall'

# easily find my IP address
alias ipaddr='curl ipecho.net/plain'

# reload .bashrc
alias reload="source $HOME/.bashrc"



# FUNCTIONS ===================================================================

# creates a directory and then immediately moves you to that directory
take() {
  mkdir -p $1;
  cd $1
}



# OTHER SOURCED FILES =========================================================

_source_if_exists() {
  if [ -f $1 ]; then
    . $1
    eval $2
  fi
}

_source_if_exists "$HOME/.prompt" # Bash prompt
_source_if_exists "$HOME/.bashrc.local" # local .bashrc overrides

unset _source_if_exists
