#!/usr/bin/env bash


# HELPER FUNCTIONS ============================================================

_source_if_exists() {
  if [ -f $1 ]; then
    . $1
    eval $2
  fi
}



# VARIABLES ===================================================================

# normalize the PATH stack
export PATH='/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin'

# add Haskell Stack exes to $PATH
export PATH="$HOME/.local/bin:$PATH" # Stack

# set the default editor to Vim
export EDITOR=vim
export VISUAL=vim



# ALIASES =====================================================================

# shortcuts for the most commonly used tools
alias v='vim'
alias g='git'

# override common tools with useful arguments
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias dir='dir --color=auto'
alias vdir='vdir --color=auto'
alias ls='ls -FG --color=auto'
alias la='ls -lah'

# attach to the tmux session or create a new named after the user
alias t='tmux attach-session -t "$(whoami)" || tmux new-session -s "$(whoami)"'

# update all Vim plugins
alias vundle='vim +PluginInstall! +qall'

# easily find my IP address
alias ipaddr='curl ipecho.net/plain'



# FUNCTIONS ===================================================================

# creates a directory and then immediately moves you to that directory
take() {
  mkdir -p $1;
  cd $1
}



# AUTO-COMPLETES ==============================================================

# use git autocompletion when "git" is aliased to "g"
if type __git_complete &>/dev/null; then
  __git_complete g __git_main
fi



# OTHER SOURCED FILES =========================================================

_source_if_exists "$HOME/.pair" # "pair() shell function to set Git pairs"
_source_if_exists "$HOME/.prompt" # Bash prompt
_source_if_exists "$HOME/.bashrc.local" # local .bashrc overrides
_source_if_exists "$HOME/.bashrc.thoughtleadr"
